version: "3.8"

services:
  primary:
    image: dvincelli/postgres:15
    container_name: primary
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    command: "-c wal-level=logical -c max-worker-processes=10 -c shared-preload-libraries=pglogical"
    volumes:
      - primary_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  replica:
    image: dvincelli/postgres:15
    container_name: replica
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    command: "-c wal-level=logical -c max-worker-processes=10 -c shared-preload-libraries='pglogical'"
    volumes:
      - replica_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    depends_on:
      - primary

  logrepl:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SOURCE_USERNAME: myuser
      SOURCE_PASSWORD: mypassword
      SOURCE_HOST: primary
      SOURCE_PORT: "5432"
      SOURCE_DBNAME: mydb
      TARGET_USERNAME: myuser
      TARGET_PASSWORD: mypassword
      TARGET_HOST: replica
      TARGET_PORT: "5432"
      TARGET_DBNAME: mydb
    command: sleep infinity

volumes:
  primary_data:
  replica_data:
